
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '6432:5432'
    networks:
      - shared

networks:
  shared:
    driver: bridge
